### ISSUE TITLE
Extract hardcoded values for default confirmations and self-delay into config

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/zeekoe#221]
We want to avoid having hardcoded parameters in zeekoe, to make it easier to run things on sandbox and testnet.

- [x] add self-delay to merchant and customer configs (in #238)
- [x] integrate self-delay into customer's origination function (in #238)
- [x] integrate self-delay into merchant's verify-origination function (in #228)

- [x] add confirmation delay to merchant and customer configs
- [x] integrate configured confirmation delay into merchant's tezos config
- [x] integrate configured confirmation delay into customer's tezos config

The merchant and customer don't need to use the same confirmation delay, but in order to avoid failure cases if, e.g., the customer delay is much smaller than the merchant's, we need to make sure that all verification functions wait an appropriate amount of time for their conditions to be satisfied, rather than failing immediately. This issue is described in #250.

| oy. I thought this was the point of sandbox vs testnet, to avoid having code like this?

_Originally posted by @indomitableSwan in https://github.com/boltlabs-inc/zeekoe/pull/186#discussion_r701985208_
